### ISSUE TITLE
Varistor alternative as well as part no. of mains connector

### ISSUE THREAD

**Issue by EarwainBanadar** [microvax2/H7864-C#1]
1. The varistor TVB7S471KR seems not to available anymore. Could you suggest and alternative?
     Not to forget that the TVB7S471KR is a SMD, not a disc type varistor.
3. The connector in the mains section in parallel to the varistor is not listed in the BOM. Of which partnumber is this connector?

**Comment by microvax2** [comment]
1. Alternative varistors added to BOM: V10E300P, MOV-10D471K. Note that any 10mm 470V disc varistor will fit OK.
2. J16-J18 Part number added to BOM: TE 640446-3 with center pin removed
3. Added Loom "J16-J18 Power Detect", spade connectors on one side and TE 640250-3 on the other side, center pin unpopulated, two pins are 3-350980-1
4. Modified main AC wiring schematic to show connection of "J16-J18 Power Detect Loom", from live/neutral to main PCB.

**Comment by EarwainBanadar** [comment]
I think there is a wrong PartNo. for item 54 in the PCB BOM.

SN74AHCT14D is a SMD type, would be SN74AC14N the correct one?
